scim: scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal > Class Template Reference
scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal > Class Template Reference
[SignalSlot]
#include <scim_signals.h>
Public Types
typedef Slot4< void, P1, P2,
P3, P4 > SlotType
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
void emit (P1 p1, P2 p2, P3 p3, P4 p4)
void operator() (P1 p1, P2 p2, P3 p3, P4 p4)
template<typename P1, typename P2, typename P3, typename P4, typename IgnoreMarshal>
class scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >
Member Typedef Documentation
template<typename P1 , typename P2 , typename P3 , typename P4 , typename IgnoreMarshal > typedef Slot4<void, P1, P2, P3, P4> scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >::SlotType
Member Function Documentation
template<typename P1 , typename P2 , typename P3 , typename P4 , typename IgnoreMarshal > Connection scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >::connect (SlotType * slot) [inline]
References scim::Signal4< R, P1, P2, P3, P4, Marshal >::connect().
template<typename P1 , typename P2 , typename P3 , typename P4 , typename IgnoreMarshal > SlotType* scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >::slot () [inline]
template<typename P1 , typename P2 , typename P3 , typename P4 , typename IgnoreMarshal > void scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >::emit (P1 p1, P2 p2, P3 p3, P4 p4) [inline]
References scim::Slot4< R, P1, P2, P3, P4 >::call(), scim::Signal::connection_list, and scim::Signal4< R, P1, P2, P3, P4, Marshal >::slot().
template<typename P1 , typename P2 , typename P3 , typename P4 , typename IgnoreMarshal > void scim::Signal4< void, P1, P2, P3, P4, IgnoreMarshal >::operator() (P1 p1, P2 p2, P3 p3, P4 p4) [inline]
References scim::Signal4< R, P1, P2, P3, P4, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h