scim: scim::Signal3< void, P1, P2, P3, IgnoreMarshal > Class Template Reference
scim::Signal3< void, P1, P2, P3, IgnoreMarshal > Class Template Reference
[SignalSlot]
#include <scim_signals.h>
Public Types
typedef Slot3< void, P1, P2, P3 > SlotType
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
void emit (P1 p1, P2 p2, P3 p3)
void operator() (P1 p1, P2 p2, P3 p3)
template<typename P1, typename P2, typename P3, typename IgnoreMarshal>
class scim::Signal3< void, P1, P2, P3, IgnoreMarshal >
Member Typedef Documentation
template<typename P1 , typename P2 , typename P3 , typename IgnoreMarshal > typedef Slot3<void, P1, P2, P3> scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::SlotType
Member Function Documentation
template<typename P1 , typename P2 , typename P3 , typename IgnoreMarshal > Connection scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::connect (SlotType * slot) [inline]
References scim::Signal3< R, P1, P2, P3, Marshal >::connect().
template<typename P1 , typename P2 , typename P3 , typename IgnoreMarshal > SlotType* scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::slot () [inline]
template<typename P1 , typename P2 , typename P3 , typename IgnoreMarshal > void scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::emit (P1 p1, P2 p2, P3 p3) [inline]
References scim::Slot3< R, P1, P2, P3 >::call(), scim::Signal::connection_list, and scim::Signal3< R, P1, P2, P3, Marshal >::slot().
template<typename P1 , typename P2 , typename P3 , typename IgnoreMarshal > void scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::operator() (P1 p1, P2 p2, P3 p3) [inline]
References scim::Signal3< R, P1, P2, P3, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h