scim: scim::Slot0< R > Class Template Reference
scim::Slot0< R > Class Template Reference
[SignalSlot]
Base class template for slots passing no arguments and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call () const =0
Calls the signal handler connected to this slot.
R operator() () const
Function operator; Calls call().
Protected Member Functions
Slot0 ()
Constructor.
Detailed Description
template<typename R>
class scim::Slot0< R >
Base class template for slots passing no arguments and returning a value of type R.
Constructor & Destructor Documentation
template<typename R > scim::Slot0< R >::Slot0 () [inline, protected]
Constructor.
Member Function Documentation
template<typename R > virtual R scim::Slot0< R >::call () const [pure virtual]
Calls the signal handler connected to this slot.
Implemented in scim::BoundSlot0_1< R, P1 >, scim::FunctionSlot0< R >, scim::MethodSlot0< T, R >, and scim::SignalSlot0< T, R >.
Referenced by scim::Signal0< void, IgnoreMarshal >::emit(), scim::Signal0< R, Marshal >::emit(), and scim::Slot0< R >::operator()().
template<typename R > R scim::Slot0< R >::operator() () const [inline]
Function operator; Calls call().
References scim::Slot0< R >::call().
The documentation for this class was generated from the following file:
scim_slot.h