scim: scim::Slot2< R, P1, P2 > Class Template Reference
scim::Slot2< R, P1, P2 > Class Template Reference
[SignalSlot]
Base class template for slots passing two arguments of type P1 and P2, and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call (P1 p1, P2 p2) const =0
Calls the signal handler connected to this slot.
R operator() (P1 p1, P2 p2) const
Function operator; Calls call().
Protected Member Functions
Slot2 ()
Constructor.
Detailed Description
template<typename R, typename P1, typename P2>
class scim::Slot2< R, P1, P2 >
Base class template for slots passing two arguments of type P1 and P2, and returning a value of type R.
Constructor & Destructor Documentation
template<typename R , typename P1 , typename P2 > scim::Slot2< R, P1, P2 >::Slot2 () [inline, protected]
Constructor.
Member Function Documentation
template<typename R , typename P1 , typename P2 > virtual R scim::Slot2< R, P1, P2 >::call (P1 p1, P2 p2) const [pure virtual]
Calls the signal handler connected to this slot.
Implemented in scim::BoundSlot2_3< R, P1, P2, P3 >, scim::FunctionSlot2< R, P1, P2 >, scim::MethodSlot2< T, R, P1, P2 >, and scim::SignalSlot2< T, R, P1, P2 >.
Referenced by scim::Signal2< void, P1, P2, IgnoreMarshal >::emit(), scim::Signal2< R, P1, P2, Marshal >::emit(), and scim::Slot2< R, P1, P2 >::operator()().
template<typename R , typename P1 , typename P2 > R scim::Slot2< R, P1, P2 >::operator() (P1 p1, P2 p2) const [inline]
Function operator; Calls call().
References scim::Slot2< R, P1, P2 >::call().
The documentation for this class was generated from the following file:
scim_slot.h