scim: scim::Signal0< void, IgnoreMarshal > Class Template Reference
scim::Signal0< void, IgnoreMarshal > Class Template Reference
[SignalSlot]
#include <scim_signals.h>
Public Types
typedef Slot0< void > SlotType
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
void emit ()
void operator() ()
template<typename IgnoreMarshal>
class scim::Signal0< void, IgnoreMarshal >
Member Typedef Documentation
template<typename IgnoreMarshal > typedef Slot0<void> scim::Signal0< void, IgnoreMarshal >::SlotType
Member Function Documentation
template<typename IgnoreMarshal > Connection scim::Signal0< void, IgnoreMarshal >::connect (SlotType * slot) [inline]
References scim::Signal0< R, Marshal >::connect().
template<typename IgnoreMarshal > SlotType* scim::Signal0< void, IgnoreMarshal >::slot () [inline]
template<typename IgnoreMarshal > void scim::Signal0< void, IgnoreMarshal >::emit () [inline]
References scim::Slot0< R >::call(), scim::Signal::connection_list, and scim::Signal0< R, Marshal >::slot().
template<typename IgnoreMarshal > void scim::Signal0< void, IgnoreMarshal >::operator() () [inline]
References scim::Signal0< R, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h