scim: scim::Slot3< R, P1, P2, P3 > Class Template Reference
scim::Slot3< R, P1, P2, P3 > Class Template Reference
[SignalSlot]
Base class template for slots passing three arguments of type P1, P2 and P3, and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call (P1 p1, P2 p2, P3 p3) const =0
Calls the signal handler connected to this slot.
R operator() (P1 p1, P2 p2, P3 p3) const
Function operator; Calls call().
Protected Member Functions
Slot3 ()
Constructor.
Detailed Description
template<typename R, typename P1, typename P2, typename P3>
class scim::Slot3< R, P1, P2, P3 >
Base class template for slots passing three arguments of type P1, P2 and P3, and returning a value of type R.
Constructor & Destructor Documentation
template<typename R , typename P1 , typename P2 , typename P3 > scim::Slot3< R, P1, P2, P3 >::Slot3 () [inline, protected]
Constructor.
Member Function Documentation
template<typename R , typename P1 , typename P2 , typename P3 > virtual R scim::Slot3< R, P1, P2, P3 >::call (P1 p1, P2 p2, P3 p3) const [pure virtual]
Calls the signal handler connected to this slot.
Implemented in scim::BoundSlot3_4< R, P1, P2, P3, P4 >, scim::FunctionSlot3< R, P1, P2, P3 >, scim::MethodSlot3< T, R, P1, P2, P3 >, and scim::SignalSlot3< T, R, P1, P2, P3 >.
Referenced by scim::Signal3< void, P1, P2, P3, IgnoreMarshal >::emit(), scim::Signal3< R, P1, P2, P3, Marshal >::emit(), and scim::Slot3< R, P1, P2, P3 >::operator()().
template<typename R , typename P1 , typename P2 , typename P3 > R scim::Slot3< R, P1, P2, P3 >::operator() (P1 p1, P2 p2, P3 p3) const [inline]
Function operator; Calls call().
References scim::Slot3< R, P1, P2, P3 >::call().
The documentation for this class was generated from the following file:
scim_slot.h