scim: scim::Signal1< void, P1, IgnoreMarshal > Class Template Reference
scim::Signal1< void, P1, IgnoreMarshal > Class Template Reference
[SignalSlot]
#include <scim_signals.h>
Public Types
typedef Slot1< void, P1 > SlotType
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
void emit (P1 p1)
void operator() (P1 p1)
template<typename P1, typename IgnoreMarshal>
class scim::Signal1< void, P1, IgnoreMarshal >
Member Typedef Documentation
template<typename P1 , typename IgnoreMarshal > typedef Slot1<void, P1> scim::Signal1< void, P1, IgnoreMarshal >::SlotType
Member Function Documentation
template<typename P1 , typename IgnoreMarshal > Connection scim::Signal1< void, P1, IgnoreMarshal >::connect (SlotType * slot) [inline]
References scim::Signal1< R, P1, Marshal >::connect().
template<typename P1 , typename IgnoreMarshal > SlotType* scim::Signal1< void, P1, IgnoreMarshal >::slot () [inline]
template<typename P1 , typename IgnoreMarshal > void scim::Signal1< void, P1, IgnoreMarshal >::emit (P1 p1) [inline]
References scim::Slot1< R, P1 >::call(), scim::Signal::connection_list, and scim::Signal1< R, P1, Marshal >::slot().
template<typename P1 , typename IgnoreMarshal > void scim::Signal1< void, P1, IgnoreMarshal >::operator() (P1 p1) [inline]
References scim::Signal1< R, P1, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h