scim: scim::Slot1< R, P1 > Class Template Reference
scim::Slot1< R, P1 > Class Template Reference
[SignalSlot]
Base class template for slots passing one argument of type P1 and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call (P1 p1) const =0
Calls the signal handler connected to this slot.
R operator() (P1 p1) const
Function operator; Calls call().
Protected Member Functions
Slot1 ()
Constructor.
Detailed Description
template<typename R, typename P1>
class scim::Slot1< R, P1 >
Base class template for slots passing one argument of type P1 and returning a value of type R.
Constructor & Destructor Documentation
template<typename R , typename P1 > scim::Slot1< R, P1 >::Slot1 () [inline, protected]
Constructor.
Member Function Documentation
template<typename R , typename P1 > virtual R scim::Slot1< R, P1 >::call (P1 p1) const [pure virtual]
Calls the signal handler connected to this slot.
Implemented in scim::BoundSlot1_2< R, P1, P2 >, scim::FunctionSlot1< R, P1 >, scim::MethodSlot1< T, R, P1 >, and scim::SignalSlot1< T, R, P1 >.
Referenced by scim::Signal1< void, P1, IgnoreMarshal >::emit(), scim::Signal1< const void, scim::Pointer & >::emit(), and scim::Slot1< R, P1 >::operator()().
template<typename R , typename P1 > R scim::Slot1< R, P1 >::operator() (P1 p1) const [inline]
Function operator; Calls call().
References scim::Slot1< R, P1 >::call().
The documentation for this class was generated from the following file:
scim_slot.h