scim: scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal > Class Template Reference
scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal > Class Template Reference
[SignalSlot]
#include <scim_signals.h>
Public Types
typedef Slot6< void, P1, P2,
P3, P4, P5, P6 > SlotType
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
void emit (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6)
void operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6)
template<typename P1, typename P2, typename P3, typename P4, typename P5, typename P6, typename IgnoreMarshal>
class scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >
Member Typedef Documentation
template<typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename P6 , typename IgnoreMarshal > typedef Slot6<void, P1, P2, P3, P4, P5, P6> scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::SlotType
Member Function Documentation
template<typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename P6 , typename IgnoreMarshal > Connection scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::connect (SlotType * slot) [inline]
References scim::Signal6< R, P1, P2, P3, P4, P5, P6, Marshal >::connect().
template<typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename P6 , typename IgnoreMarshal > SlotType* scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::slot () [inline]
template<typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename P6 , typename IgnoreMarshal > void scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::emit (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) [inline]
References scim::Slot6< R, P1, P2, P3, P4, P5, P6 >::call(), scim::Signal::connection_list, and scim::Signal6< R, P1, P2, P3, P4, P5, P6, Marshal >::slot().
template<typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename P6 , typename IgnoreMarshal > void scim::Signal6< void, P1, P2, P3, P4, P5, P6, IgnoreMarshal >::operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5, P6 p6) [inline]
References scim::Signal6< R, P1, P2, P3, P4, P5, P6, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h