scim: scim::Signal5< R, P1, P2, P3, P4, P5, Marshal > Class Template Reference
scim::Signal5< R, P1, P2, P3, P4, P5, Marshal > Class Template Reference
[SignalSlot]
A template for a signal passing five arguments of type P1, P2, P3, P4 and P5, and returning a value of type R.
#include <scim_signals.h>
Public Types
typedef Slot5< R, P1, P2, P3,
P4, P5 > SlotType
Function signature for handlers connecting to the signal.
Public Member Functions
Connection connect (SlotType *slot)
SlotType * slot ()
R emit (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5)
R operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5)
Function operator; calls emit().
Detailed Description
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5, typename Marshal = class DefaultMarshal<R>>
class scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >
A template for a signal passing five arguments of type P1, P2, P3, P4 and P5, and returning a value of type R.
Member Typedef Documentation
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename Marshal = class DefaultMarshal<R>> typedef Slot5<R, P1, P2, P3, P4, P5> scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::SlotType
Function signature for handlers connecting to the signal.
Member Function Documentation
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename Marshal = class DefaultMarshal<R>> Connection scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::connect (SlotType * slot) [inline]
Connect a slot to the signal.
Parameters:
slot - a slot of type Slot5<R, P1, P2, P3, P4, P5>.
Returns:
a connection object.
The returned connection object can be used alter or change the connection.
Referenced by scim::Signal5< void, P1, P2, P3, P4, P5, IgnoreMarshal >::connect().
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename Marshal = class DefaultMarshal<R>> SlotType* scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::slot () [inline]
Returns a slot for this signal.
Returns:
a new slot of type Slot5<R, P1, P2, P3, P4, P5>.
The returned slot can be passed to another signal allowing the other signal to call this signal when it gets emitted.
Referenced by scim::Signal5< void, P1, P2, P3, P4, P5, IgnoreMarshal >::emit(), and scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::emit().
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename Marshal = class DefaultMarshal<R>> R scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::emit (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) [inline]
Emit the signal.
Parameters:
p1 - passes p1 to the signal handler.
p2 - passes p2 to the signal handler.
p3 - passes p3 to the signal handler.
p4 - passes p4 to the signal handler.
p5 - passes p5 to the signal handler.
Returns:
the value returned by the signal handler.
Calls every slot connected to this signal, in order of connection.
References scim::Slot5< R, P1, P2, P3, P4, P5 >::call(), scim::Signal::connection_list, and scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::slot().
Referenced by scim::Signal5< void, P1, P2, P3, P4, P5, IgnoreMarshal >::operator()(), and scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::operator()().
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 , typename Marshal = class DefaultMarshal<R>> R scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) [inline]
Function operator; calls emit().
References scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::emit().
The documentation for this class was generated from the following file:
scim_signals.h