scim: scim::Slot5< R, P1, P2, P3, P4, P5 > Class Template Reference
scim::Slot5< R, P1, P2, P3, P4, P5 > Class Template Reference
[SignalSlot]
Base class template for slots passing five arguments of type P1, P2, P3, P4 and P5, and returning a value of type R.
#include <scim_slot.h>
Public Member Functions
virtual R call (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) const =0
Calls the signal handler connected to this slot.
R operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) const
Function operator; Calls call().
Protected Member Functions
Slot5 ()
Detailed Description
template<typename R, typename P1, typename P2, typename P3, typename P4, typename P5>
class scim::Slot5< R, P1, P2, P3, P4, P5 >
Base class template for slots passing five arguments of type P1, P2, P3, P4 and P5, and returning a value of type R.
Constructor & Destructor Documentation
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 > scim::Slot5< R, P1, P2, P3, P4, P5 >::Slot5 () [inline, protected]
Member Function Documentation
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 > virtual R scim::Slot5< R, P1, P2, P3, P4, P5 >::call (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) const [pure virtual]
Calls the signal handler connected to this slot.
Implemented in scim::BoundSlot5_6< R, P1, P2, P3, P4, P5, P6 >, scim::FunctionSlot5< R, P1, P2, P3, P4, P5 >, scim::MethodSlot5< T, R, P1, P2, P3, P4, P5 >, and scim::SignalSlot5< T, R, P1, P2, P3, P4, P5 >.
Referenced by scim::Signal5< void, P1, P2, P3, P4, P5, IgnoreMarshal >::emit(), scim::Signal5< R, P1, P2, P3, P4, P5, Marshal >::emit(), and scim::Slot5< R, P1, P2, P3, P4, P5 >::operator()().
template<typename R , typename P1 , typename P2 , typename P3 , typename P4 , typename P5 > R scim::Slot5< R, P1, P2, P3, P4, P5 >::operator() (P1 p1, P2 p2, P3 p3, P4 p4, P5 p5) const [inline]
Function operator; Calls call().
References scim::Slot5< R, P1, P2, P3, P4, P5 >::call().
The documentation for this class was generated from the following file:
scim_slot.h